name: Hello World

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:
    inputs:
      requested_for: 
        required: true
      ritm: 
        required: true
      reason:
        description: 'Reason for manual trigger'
        required: false

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
    - name: Greetings
      run: echo "Hello, world! Welcome" >> ${{ github.event.inputs.ritm }}
    outputs:
      output1: echo "Executed"
